### ISSUE TITLE
Paper link is not working

### ISSUE THREAD

**Issue by RahulSundar** [ShotaDeguchi/DN_PINN#2]
Dear Shota Deguchi,

I am unable to find your recent paper. Please let me know if there is an online preprint that I can access. 

Thanks 
Rahul Sundar

**Comment by ShotaDeguchi** [comment]
Dear Rahul Sundar,

Thank you for contacting me and sorry for the delay in responding. 

The preprint is not available (sorry for the confusion in readme), but it is part of a paper already accepted in a journal. 
We are now waiting for the publication and will update the information upon the publication. 

Kind regards,
Shota Deguchi

**Comment by RahulSundar** [comment]
Dear Shota,

Thanks for getting back. I await the paper :)

Thank you
Rahul Sundar

**Comment by ShotaDeguchi** [comment]
Dear Rahul,

Thank you, will update you when it is available. 

Regards,
Shota Deguchi

**Comment by ShotaDeguchi** [comment]
Dear Rahul,

Thanks again for pointing this out, the information is now updated. 

Closing this issue. 

Sincerely,
Shota Deguchi
